name: Build STM32 Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install ARM GCC toolchain
      run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi make

    - name: Build project
      run: make
